# Generated by Django 4.2.7 on 2023-12-03 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_generator", "0003_quiz"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz_date", models.DateField(auto_now_add=True)),
                ("score", models.IntegerField()),
                ("num_correct", models.IntegerField()),
                ("num_wrong", models.IntegerField()),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_generator.quiz",
                    ),
                ),
            ],
        ),
    ]
